name: build-x86-64-immortalwrt-24.10.0

on:
  workflow_dispatch:
    inputs:
      profile:
        description: '请输入要编译固件大小 单位(MB)'
        required: true
        default: '2048'
      include_docker:
        description: |
          是否编译 Docker 插件
        required: true
        default: 'yes'
        type: choice
        options:
          - 'yes'
          - 'no'
      enable_pppoe:
        description: "是否配置PPPoE拨号信息?"
        required: true
        default: 'no'
        type: choice
        options:
        - 'yes'
        - 'no'
      pppoe_account:
        description: "宽带账号 (若启用PPPoE)"
        required: false
      pppoe_password:
        description: "宽带密码 (若启用PPPoE)"
        required: false

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout OpenWrt code with submodules
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'  # 确保获取 OpenWrt 仓库的子模块

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git

      - name: Clone OpenWrt source repository
        run: |
          git clone --depth 1 https://github.com/openwrt/openwrt.git ${{ github.workspace }}/x86-64
          cd ${{ github.workspace }}/x86-64
          git submodule update --init --recursive  # 确保拉取所有子模块

      - name: List directory contents
        run: |
          cd ${{ github.workspace }}/x86-64
          ls -al  # 查看文件夹内容，确保scripts目录存在

      - name: Validate PPPoE Inputs
        run: |
          if [[ "${{ inputs.enable_pppoe }}" == "yes" ]]; then
            if [[ -z "${{ inputs.pppoe_account }}" || -z "${{ inputs.pppoe_password }}" ]]; then
              echo "Error: PPPoE account and password must be provided when PPPoE is enabled!"
              exit 1
            fi
          fi

      - name: Compilation Step
        run: |
          # Navigate to the OpenWrt source directory
          cd ${{ github.workspace }}/x86-64
          
          # add feed
          echo "src-git nikki https://github.com/nikkinikki-org/OpenWrt-nikki.git;main" >> "feeds.conf.default"
          
          # update & install feeds
          ./scripts/feeds update -a
          ./scripts/feeds install -a

          # make package
          make package/luci-app-nikki/compile
          
          echo "The ipk/apk file will be found under bin/packages/your_architecture/nikki."